# Generated by Django 5.2.6 on 2025-09-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(blank=True, max_length=50)),
                ('edad', models.IntegerField()),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('adoptada', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
            ],
        ),
    ]
