# Generated by Django 5.2.6 on 2025-09-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_adoptante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adoptante',
        ),
    ]
