# Generated by Django 5.2.6 on 2025-10-12 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_delete_adoptante'),
        ('usuarios', '0007_refugio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='refugio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='usuarios.refugio'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], default='M', max_length=1),
        ),
        migrations.DeleteModel(
            name='Refugio',
        ),
    ]
