# Generated by Django 5.2.6 on 2025-10-12 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0008_auto_20251012_1513'),
        ('usuarios', '0007_refugio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='refugio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='usuarios.refugio'),
        ),
    ]
