# Generated by Django 5.2.6 on 2025-09-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_adoptante_fecha_modificacion_adoptante_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
