# Generated by Django 5.2.6 on 2025-09-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_adoptante_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptante',
            name='avatar',
            field=models.CharField(blank=True, choices=[('avatar1.png', 'Avatar 1'), ('avatar2.png', 'Avatar 2'), ('avatar3.png', 'Avatar 3'), ('avatar4.png', 'Avatar 4'), ('avatar5.png', 'Avatar 5')], max_length=100),
        ),
    ]
