# Generated by Django 5.2.6 on 2025-09-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_adoptante_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptante',
            name='foto_perfil',
        ),
    ]
