# Generated by Django 5.2.6 on 2025-09-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_adoptante_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptante',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
