# Generated by Django 5.2.6 on 2025-11-03 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_refugio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptante',
            name='avatar',
        ),
    ]
