# Generated by Django 5.2.6 on 2025-11-08 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_adoptante_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veterinarios', to='usuarios.refugio')),
            ],
        ),
    ]
