# Generated by Django 5.2.6 on 2025-11-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_veterinario'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinario',
            name='apellido',
            field=models.CharField(default='Sin apellido', max_length=100),
        ),
    ]
