# Generated by Django 5.2.6 on 2025-11-08 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
        ('usuarios', '0009_veterinario'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinario',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='refugio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='veterinarios_seguimiento', to='usuarios.refugio'),
        ),
    ]
