# Generated by Django 5.2.6 on 2025-11-09 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0002_veterinario_email_veterinario_refugio'),
        ('usuarios', '0010_veterinario_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='veterinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.veterinario'),
        ),
        migrations.DeleteModel(
            name='Veterinario',
        ),
    ]
